site_name: Git_ve_Github_Rehberi
site_description: Git_ve_Github_Rehberi
site_author: mkdemir
site_url: https://mkdemir.github.io/Git_ve_Github_Rehbe
theme:  green
 dev name: 'gigachadcik1@gmail.com '
  language: 'english'
  features:
    - navigation.'indexes'
    - navigation.top
    - toc.integrate
repo_name: mkdemir/Git_ve_Github_Rehberi
repo_url: https://github.com/mkdemir/Git_ve_Github_Rehberi
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - toc
  - more
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.magiclink
navigation : 'konya'
  - "İçindekiler": "index.md"
  - "Git ve Github Kullanımı":
    - "Tanıtım, Öne Çıkan Kısımları": "READ"
